name: Traffic

on:
  workflow_dispatch:

jobs:
  run-traffic:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Cache Chromium Binary
        uses: actions/cache@v4.2.3
        with:
          path: /usr/bin/chromium-browser
          key: chromium-cache-${{ runner.os }}
          restore-keys: chromium-cache-

      - name: Install Chromium Browser
        run: sudo apt-get install -y chromium-browser

      - name: Install Puppeteer & Plugins
        run: npm install puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Display Current IP
        run: curl https://api.ipify.org

      - name: Run Traffic Script
        run: node main.js
