name: Traffic

on:
  workflow_dispatch:

jobs:
  run-traffic-script:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Chromium browser
        uses: actions/cache@v4.2.3
        with:
          path: /home/runner/chromium-browser
          key: Linux-chromium-${{ runner.os }}
          restore-keys: |
            Linux-chromium-
          enableCrossOsArchive: false
          fail-on-cache-miss: false
          lookup-only: false
          save-always: false

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Install dependencies
        run: |
          npm ci
          npm install puppeteer-core
          npm install puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Set Chromium path
        run: |
          echo "CHROME_PATH=/home/runner/chromium-browser/chrome" >> $GITHUB_ENV

      - name: Display current IP address
        run: curl ifconfig.me

      - name: Run Traffic script
        run: node main.js
        env:
          CHROME_PATH: ${{ env.CHROME_PATH }}
