name: Traffic

on:
  push:
    branches: [main]

jobs:
  run-traffic:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Install Chromium via apt
        run: sudo apt-get install -y chromium

      - name: Cache Chromium Binary
        uses: actions/cache@v4.2.3
        with:
          path: /usr/bin/chromium
          key: Linux-chromium-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            Linux-chromium-

      - name: Install Dependencies
        run: |
          npm install puppeteer-core puppeteer-extra

      - name: Display Current IP Address
        run: curl https://api.ipify.org

      - name: Run Traffic Script
        run: node main.js
