name: Traffic
on:
  workflow_dispatch:

jobs:
  traffic-job:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Install Chromium
        run: |
          sudo apt-get install -y chromium-browser
          ln -sf /usr/bin/chromium-browser /home/runner/chromium-browser

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Run Traffic script repeatedly
        run: |
          START=$(date +%s)
          while true; do
            echo "Running main.js..."
            node main.js || echo "main.js exited with error"
            NOW=$(date +%s)
            ELAPSED=$(( (NOW - START) / 60 ))
            echo "Elapsed time: $ELAPSED minutes"
            if [ "$ELAPSED" -ge 330 ]; then
              echo "Reached 5h30m, exiting with 0"
              break
            fi
          done

      - name: Trigger this workflow again
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Re-triggering the same workflow..."
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/traffic.yml/dispatches \
            -d '{"ref":"${{ github.ref_name }}"}'
