name: Traffic

on:
  workflow_dispatch:

jobs:
  traffic:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Chromium
        uses: actions/cache@v4.2.3
        with:
          path: /home/runner/chromium-browser
          key: ${{ runner.os }}-chromium-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-chromium-

      - name: Install Dependencies
        run: npm install puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Show External IP
        run: curl ifconfig.me

      - name: Run Traffic Script
        run: node main.js
