name: Traffic

on:
  workflow_dispatch:

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser xvfb curl

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies without Chromium
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
        run: npm install puppeteer-extra puppeteer-extra-plugin-stealth

      - name: Start Xvfb (Simulate GUI)
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Show public IP address
        run: |
          echo "Current Public IP:"
          curl https://api.ipify.org

      - name: Run Puppeteer script
        env:
          DISPLAY: ':99.0'
        run: |
          node main.js
